### PR TITLE
breaking change: make `UserLinks.{likes,followers,following}` and `PhotoStatistics.likes` nullable to adapt to changed API response

### LINKED ISSUE #24: `UserLinks.followers` is null sometimes and thus it should not be required
Hi!

A project of mine started failing as line 234 of `/lib/src/model/user.dart` was trying to cast a Null to String.
Possibly a recent change in the Unsplash API 🤷‍♂️

Solved it locally by making the field optional.

Opening an issue here to notify you.

Thanks for your work!

### PR DESCRIPTION
**Pull request by christenbc**
```
#0      new UserLinks.fromJson (package:unsplash_client/src/model/user.dart:234:37)
#1      new User.fromJson.<anonymous closure> (package:unsplash_client/src/model/user.dart:119:34)
#2      ObjectUtils.let (package:unsplash_client/src/utils.dart:10:35)
#3      new User.fromJson (package:unsplash_client/src/model/user.dart:119:12)
#4      new Photo.fromJson (package:unsplash_client/src/model/photo.dart:146:20)
#5      _deserializePhotos.<anonymous closure> (package:unsplash_client/src/photos.dart:169:54)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#7      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#8      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#9      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#10     new List.of (dart:core-patch/array_patch.dart:39:18)
#11     ListIterable.toList (dart:_internal/iterable.dart:224:7)
#12     deserializeObjectList (package:unsplash_client/src/utils.dart:34:65)
#13     _deserializePhotos (package:unsplash_client/src/photos.dart:169:10)
#14     Request.go (package:unsplash_client/src/client.dart:212:31)
<asynchronous suspension>
#15     RequestExtension.goAndGet (package:unsplash_client/src/client.dart:383:13)
<asynchronous suspension>
#16     _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:638:31)
<asynchronous suspension>
```

### CODE REVIEW

File: lib/src/model/user.dart [hunk 1]
```diff
@@ -223,16 +220,28 @@ class UserLinks extends ModelBase {
...
-      likes: (json['likes'] as String).let(Uri.parse),
-      portfolio: (json['portfolio'] as String).let(Uri.parse),
-      followers: (json['followers'] as String).let(Uri.parse),
-      following: (json['following'] as String).let(Uri.parse),
+      self: (json['self'] as String?)?.let(Uri.parse) ?? Uri(),
+      html: (json['html'] as String?)?.let(Uri.parse) ?? Uri(),
+      photos: (json['photos'] as String?)?.let(Uri.parse) ?? Uri(),
+      likes: (json['likes'] as String?)?.let(Uri.parse) ?? Uri(),
+      portfolio: (json['portfolio'] as String?)?.let(Uri.parse) ?? Uri(),
+      followers: (json['followers'] as String?)?.let(Uri.parse) ?? Uri(),
```
Comment (blaugold) [inline lib/src/model/user.dart]: The exception is thrown when trying to parse `followers`:

https://github.com/blaugold/unsplash_client/blob/e29ab00b1e4a80e79ebd6e6b2db9e720cb02491a/lib/src/model/user.dart#L234

Can we just make `followers` nullable in `UserLinks`?

I would rather make a breaking change than return empty `Uri`s or `UserLinks` without any links.

File: lib/src/model/user.dart [hunk 2]
```diff
@@ -223,16 +220,28 @@ class UserLinks extends ModelBase {
     };
   }
 
-  factory UserLinks.fromJson(Map<String, dynamic> json) {
+  factory UserLinks.fromJson(Map<String, dynamic>? json) {
```
Comment (blaugold) [inline lib/src/model/user.dart]: Have you seen responses does not have any user links, or are you trying to be defensive? I would rather have the models reflect that a field might not be available by making it nullable. But only if it actually is optional.

**Review by blaugold — CHANGES_REQUESTED** [review]
Thanks for contributing! 🎉

**Comment by farosato** [comment]
I've only seen responses with no `UserLinks.followers`.
Locally I fixed it by making `followers`, `following`, and `likes` optional just in case (as they are all minor count fields that could reasonably all be equally null).
I actively use `UserLinks.html` and I haven't seen any response with no UserLinks at all, so I wouldn't go as far as making UserLinks entirely optional.
